"""Structured retrieval and generation evaluation."""

from filing_rag.evaluate.golden import QuoteCheckError, check_quotes, load_golden
from filing_rag.evaluate.metrics import (
    collapse_sections,
    mean_scores,
    mrr,
    ndcg_at,
    recall_at,
    score_question,
)
from filing_rag.evaluate.pipeline import Evaluator, Searcher, eval_grid
from filing_rag.evaluate.rag import Answerer, RagEvaluator, winning_strategy
from filing_rag.evaluate.ragas import (
    CollectionsRagasScorer,
    RagasError,
    RagasScorer,
    RagasScores,
    mean_ragas,
)
from filing_rag.evaluate.refusal import is_refusal, refusal_rate
from filing_rag.evaluate.report import (
    ABLATION_END,
    ABLATION_START,
    inject_readme,
    render_ablation,
    run_report,
)
from filing_rag.evaluate.store import (
    JSONL_NAME,
    RAG_JSONL_NAME,
    format_rag_summary,
    format_rag_table,
    format_summary,
    format_table,
    load_jsonl,
    load_rag_jsonl,
    percentile,
    write_jsonl,
    write_rag_jsonl,
)
from filing_rag.evaluate.types import (
    EVAL_K,
    ITEM_CODES,
    NDCG_K,
    QUESTION_TYPES,
    RECALL_KS,
    Citation,
    ConfigReport,
    EvalResult,
    GoldenSet,
    GridConfig,
    MeanScore,
    QueryRow,
    QueryScore,
    Question,
    RagConfigReport,
    RagEvalResult,
    RagQueryRow,
)

__all__ = [
    "EVAL_K",
    "ITEM_CODES",
    "JSONL_NAME",
    "NDCG_K",
    "QUESTION_TYPES",
    "RAG_JSONL_NAME",
    "RECALL_KS",
    "ABLATION_END",
    "ABLATION_START",
    "Answerer",
    "Citation",
    "CollectionsRagasScorer",
    "ConfigReport",
    "EvalResult",
    "Evaluator",
    "GoldenSet",
    "GridConfig",
    "MeanScore",
    "QueryRow",
    "QueryScore",
    "Question",
    "QuoteCheckError",
    "RagConfigReport",
    "RagEvalResult",
    "RagEvaluator",
    "RagQueryRow",
    "RagasError",
    "RagasScores",
    "RagasScorer",
    "Searcher",
    "check_quotes",
    "collapse_sections",
    "eval_grid",
    "format_rag_summary",
    "format_rag_table",
    "format_summary",
    "format_table",
    "inject_readme",
    "is_refusal",
    "load_golden",
    "load_jsonl",
    "load_rag_jsonl",
    "mean_ragas",
    "mean_scores",
    "mrr",
    "ndcg_at",
    "percentile",
    "recall_at",
    "refusal_rate",
    "render_ablation",
    "run_report",
    "score_question",
    "winning_strategy",
    "write_jsonl",
    "write_rag_jsonl",
]
